x=float(input("enter value of x:"))
y=float(input("enter value of y:"))
print("calculate the value of the expression :")
print(" (1+x/y +x^y)/(2+y/x +y^x)")
print((1+(x/y)+(x**y))/(2 + (y/x) +(y**x)))
print("done")
