print( ' "compute the value of following algebraic expression : " ')
print(' " ax^5 + bx^4 +cx^3 +dx^2 + ex +f " ')
x = float(input("Enter the value of variable x : "))
a=float(input("Enter the value of a :"))
b=float(input("Enter the value of b:"))
c=float(input("Enter the value of c :"))
d=float(input("Enter the value of d :"))
e=float(input("Enter the value of e :"))
f=float(input("Enter the value of f :"))
print((a*(x**5)) + (b*(x**4)) + (c*(x**3)) +(d*(x**2)) +(e*x) + (f) )
