a1=float(input("enter first number:"))
a2=float(input("enter second number:"))
a3=float(input("enter third number:"))
a4=float(input("enter fourth number:"))
a5=float(input("enter fifth number:"))
print("average of the above five numbers is :" + str((a1+a2+a3+a4+a5)/5))
print("done")
